# Generated by Django 3.2.3 on 2021-06-18 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosZapatilla',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Nombre de Zapatilla')),
                ('valor', models.IntegerField(verbose_name='Valor')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('imagen', models.ImageField(upload_to='zapatillas')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de Marca')),
                ('nombreMarca', models.CharField(max_length=100, verbose_name='nombre de Marca')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
        migrations.AddField(
            model_name='datoszapatilla',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marca'),
        ),
    ]
