# Generated by Django 3.2.3 on 2021-06-19 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_datoszapatilla_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datoszapatilla',
            name='imagen',
        ),
    ]
