# Generated by Django 3.2.3 on 2021-06-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_datoszapatilla_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoszapatilla',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='zapatillas/'),
        ),
    ]
