# Generated by Django 3.2.3 on 2021-06-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_datoszapatilla_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoszapatilla',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
