# Generated by Django 3.2.3 on 2021-06-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_datoszapatilla_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoszapatilla',
            name='fecha',
            field=models.CharField(max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='datoszapatilla',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='zapatillas'),
        ),
    ]
