# Generated by Django 3.2.3 on 2021-06-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210620_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoszapatilla',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='zapatillas/'),
        ),
    ]
